name: CI-CD
on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Scan
        run: |
          echo "Ejecutando analisis de sonar..."
          # La palabra sonar es obligatoria para el check T5